import site from "../site.json" with { type: "json" };

const units = [
  { id: "construction-shower", family: "shower", familyRole: "primary", eyebrow: "CONSTRUCTION SHOWER RENTAL", title: "Shower trailer rental for construction crews.", text: "Plan private, climate-controlled washing capacity around shift size, site access, hot water and wastewater service.", image: "/images/service-heroes/20ft-shower-trailer-sink/01-960.webp", alt: "Commercial shower stall inside a 20 ft construction shower trailer rental", caption: "Approved 20 ft five-stall shower trailer rental reference with commercial fixtures.", href: "/equipment-rental/shower-trailer/" },
  { id: "emergency-shower", family: "shower", familyRole: "primary", eyebrow: "EMERGENCY SHOWER RENTAL", title: "Temporary shower trailer rental for response sites.", text: "Coordinate shower capacity for emergency basecamps, restoration work and temporary operations after an outage.", image: "/images/service-heroes/20ft-shower-trailer-sink/02-960.webp", alt: "Commercial fixtures inside an emergency shower trailer rental", caption: "Approved five-stall shower trailer rental interior; confirm delivery, utilities and servicing.", href: "/equipment-rental/shower-trailer/" },
  { id: "industrial-shower", family: "shower", familyRole: "primary", eyebrow: "INDUSTRIAL SHOWER RENTAL", title: "Commercial shower trailer rental for industrial sites.", text: "Match private shower facilities to rotating shifts, remote access, safety planning and the project schedule.", image: "/images/service-heroes/20ft-shower-trailer-sink/03-960.webp", alt: "Private stall in a commercial industrial shower trailer rental", caption: "Approved commercial shower trailer rental stall for workforce planning.", href: "/equipment-rental/shower-trailer/" },
  { id: "institutional-shower", family: "shower", familyRole: "primary", eyebrow: "FACILITY SHOWER RENTAL", title: "Shower trailer leasing for occupied facilities.", text: "Maintain temporary washing access during planned renovations at healthcare, education and government facilities.", image: "/images/service-heroes/20ft-shower-trailer-sink/04-960.webp", alt: "Sink and shower fixtures in an institutional shower trailer lease unit", caption: "Approved shower trailer leasing reference; confirm the actual floor plan and accessible route.", href: "/equipment-rental/shower-trailer/" },
  { id: "event-shower", family: "shower", familyRole: "primary", eyebrow: "EVENT SHOWER RENTAL", title: "Portable shower trailer rental for commercial events.", text: "Give staff, athletes and scheduled participants private washing space with a documented servicing plan.", image: "/images/service-heroes/20ft-shower-trailer-sink/05-960.webp", alt: "Interior handwashing fixtures in a portable event shower trailer rental", caption: "Approved portable shower trailer rental reference for commercial event planning.", href: "/equipment-rental/shower-trailer/" },
  { id: "remote-shower-container", family: "shower", familyRole: "primary", eyebrow: "REMOTE SHOWER RENTAL", title: "Shower container rental for remote operations.", text: "Review container delivery, placement, hot-water supply and drainage for longer remote assignments.", image: "/images/service-heroes/20ft-shower-container/01-960.webp", alt: "Commercial stall inside a 20 ft remote-site shower container rental", caption: "Approved 20 ft five-stall shower container rental reference; delivery differs from a trailer.", href: "/services/shower-containers/20ft-5-stall/" },
  { id: "workforce-shower-container", family: "shower", familyRole: "primary", eyebrow: "WORKFORCE SHOWER RENTAL", title: "Long-term shower container rental for workforce camps.", text: "Plan private washing capacity around crew count, peak demand, utilities and recurring wastewater service.", image: "/images/service-heroes/20ft-shower-container/02-960.webp", alt: "Private commercial fixture in a workforce shower container rental", caption: "Approved shower container rental interior for workforce-camp planning.", href: "/services/shower-containers/20ft-5-stall/" },
  { id: "renovation-shower-container", family: "shower", familyRole: "primary", eyebrow: "RENOVATION SHOWER RENTAL", title: "Temporary shower container rental during renovations.", text: "Keep essential washing facilities available while permanent rooms are repaired or replaced.", image: "/images/service-heroes/20ft-shower-container/03-960.webp", alt: "Temporary shower container rental interior for a facility renovation", caption: "Approved temporary shower container rental reference; confirm placement and connections.", href: "/services/shower-containers/20ft-5-stall/" },
  { id: "combination-support", family: "shower-restroom-combination", familyRole: "supporting", eyebrow: "COMBINATION RENTAL", title: "Shower and restroom combination trailer rental.", text: "Use one commercial facility for washing and toilet access when the verified stall plan fits the site.", image: "/images/service-heroes/13ft-shower-restroom-combination/01-960.webp", alt: "Interior of a commercial shower and restroom combination trailer rental", caption: "Approved 13 ft shower and restroom combination trailer rental reference; confirm the stall layout.", href: "/services/shower-restroom-combination-trailers/" },
  { id: "kitchen-support", family: "mobile-commercial-kitchen", familyRole: "supporting", eyebrow: "KITCHEN SUPPORT RENTAL", title: "Mobile commercial kitchen trailer rental.", text: "Add temporary food-production space when a basecamp, institution or active project also needs meal service.", image: "/images/service-heroes/24ft-mobile-kitchen/01-960.webp", alt: "Interior of a 24 ft mobile commercial kitchen trailer rental", caption: "Approved 24 ft mobile commercial kitchen trailer rental reference; confirm equipment and layout.", href: "/inventory/mobile-kitchen-models/" },
];
const industries = [
  ["CS", "Construction sites", "Keep crews clean and productive through multi-week and multi-month builds."],
  ["GM", "Government & military", "Support disaster response, public works, military and emergency-management operations."],
  ["EF", "Events & festivals", "Provide comfortable shower and restroom access for outdoor events, weddings and sporting programs."],
  ["HF", "Healthcare facilities", "Support staff hygiene during renovations, outages or emergency facility work."],
  ["EC", "Educational campuses", "Keep housing, athletics and campus operations moving during renovations or response work."],
  ["EI", "Energy & industrial", "Plan heavy-duty configurations, hot water and remote-site logistics for industrial operations."],
];
const faqs = [
  ["How much does a shower trailer rental cost?", "Pricing depends on the unit, occupancy, location, rental duration, site access, utilities and servicing plan. Share those details for a project-specific quote."],
  ["How quickly can a shower trailer be delivered?", "Delivery timing depends on availability, route, site readiness and the requested date. The rental team confirms the schedule before an agreement is finalized."],
  ["Are ADA-accessible shower trailers available?", "Accessible configurations may be available. Confirm the actual floor plan, access route, ramp and site requirements with the rental team."],
  ["Do you offer long-term shower trailer rentals?", "Yes. Discuss short-term or extended rental needs, servicing, delivery and removal timing with the project team."],
  ["Do you hold a GSA Schedule contract?", "Government buyers should confirm the current contract details and purchasing path with the rental specialist before relying on a procurement claim."],
];

export function Home() {
  return <div className="shower-home">
    <section className="shower-hero" aria-labelledby="shower-hero-title"><div className="shower-hero-panel" data-family-content data-family="shower" data-family-role="primary"><span className="shower-kicker">TEMPORARY SHOWER RENTAL 123 · NATIONWIDE</span><h1 id="shower-hero-title">Temporary Shower Trailer Rental</h1><p>Commercial shower trailer rental and leasing for construction sites, institutional renovations, events, remote operations and emergency basecamps.</p><div className="shower-actions"><a className="button" href={`tel:${site.phoneE164}`}>Call {site.phoneDisplay}</a><a className="button secondary" href="/contact-us/">Request a quote</a></div><div className="shower-hero-facts"><span><strong>24/7</strong> live agent support</span><span><strong>50</strong> states served</span><span><strong>2–5</strong> day standard delivery*</span></div></div><figure className="shower-hero-image" data-family-visual data-family="shower" data-family-role="primary"><img src="/images/service-heroes/20ft-shower-trailer-sink/01-960.webp" alt="Commercial shower stall inside a temporary shower trailer rental" width="960" height="640" fetchPriority="high" /><figcaption>Approved 20 ft five-stall shower trailer rental reference with commercial fixtures.</figcaption></figure></section>
    <section className="shower-section shower-intro" aria-labelledby="solutions-title"><div><span className="shower-kicker">COMMERCIAL SHOWER SOLUTIONS</span><h2 id="solutions-title">Clean facilities for work that cannot pause.</h2></div><p>Professionally maintained shower trailers and shower containers support construction, government projects, healthcare facilities, schools and commercial events. Confirm the available unit, utilities, access and delivery plan for your site.</p></section>
    <section className="shower-facts" aria-label="Service facts"><div><strong>24/7</strong><span>Live agent support</span></div><div><strong>50</strong><span>States served</span></div><div><strong>2–5</strong><span>Day standard delivery*</span></div><div><strong>GSA</strong><span>Verify current contract details</span></div></section>
    <section className="shower-section" aria-labelledby="industries-title"><span className="shower-kicker">INDUSTRIES WE SERVE</span><h2 id="industries-title">Commercial shower trailers built around your operation.</h2><div className="shower-industry-grid">{industries.map(([code, title, text]) => <article key={title}><span className="shower-industry-code">{code}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section>
    <section className="shower-section shower-units" aria-labelledby="units-title"><div className="shower-section-heading"><div><span className="shower-kicker">EXPLORE THE FLEET</span><h2 id="units-title">Start with shower capacity, then add site support.</h2></div><a className="text-link" href="/equipment-rental/">View all rental options ↗</a></div><div className="shower-unit-grid">{units.map((unit) => <article className={`shower-unit-card shower-unit-card--${unit.familyRole}`} key={unit.id} data-family-content data-family={unit.family} data-family-role={unit.familyRole}><figure data-family-visual data-family={unit.family} data-family-role={unit.familyRole}><img src={unit.image} alt={unit.alt} loading="lazy" width="960" height="640" /><figcaption>{unit.caption}</figcaption></figure><div><span className="shower-kicker">{unit.eyebrow}</span><h3>{unit.title}</h3><p>{unit.text}</p><a className="text-link" href={unit.href}>Explore this option ↗</a></div></article>)}</div></section>
    <section className="shower-section shower-included" aria-labelledby="included-title"><div><span className="shower-kicker">WHAT'S INCLUDED</span><h2 id="included-title">Comfort, privacy and dependable site support.</h2></div><div className="shower-included-grid"><p><strong>Climate-controlled comfort</strong> Year-round heating and air conditioning for changing conditions.</p><p><strong>Continuous hot water</strong> Commercial-grade water heaters for every shift or guest.</p><p><strong>Private, secure stalls</strong> Individual lockable shower compartments for privacy.</p><p><strong>Accessible options</strong> Confirm the actual ADA layout and access requirements for the selected unit.</p><p><strong>Safety flooring</strong> Slip-resistant floors designed for clean, safe step-in showering.</p><p><strong>Self-contained supply</strong> Review onboard water, power, drainage and servicing for remote sites.</p></div></section>
    <section className="shower-section shower-faq" aria-labelledby="faq-title"><span className="shower-kicker">FREQUENTLY ASKED QUESTIONS</span><h2 id="faq-title">Clear answers before you schedule.</h2><div className="shower-faq-list">{faqs.map(([question, answer]) => <details key={question}><summary>{question}<span aria-hidden="true">+</span></summary><p>{answer}</p></details>)}</div></section>
    <section className="shower-cta" aria-labelledby="cta-title"><span className="shower-kicker">READY TO PLAN?</span><h2 id="cta-title">Need a temporary shower trailer or shower container?</h2><p>Tell the logistics team about crew capacity, site footprint, utilities and scheduling.</p><div className="shower-actions"><a className="button" href={`tel:${site.phoneE164}`}>Call now: {site.phoneDisplay}</a><a className="button secondary" href="/contact-us/">Request a quote</a></div></section><p className="shower-disclaimer">*Delivery timing, availability, pricing and contract terms require confirmation for the actual project.</p>
  </div>;
}
