import site from "../site.json" with { type: "json" };

const units = [
  { eyebrow: "SHOWER TRAILERS", title: "Private showers, ready for the job site.", text: "Clean, climate-controlled shower capacity for construction crews, events, renovations and emergency response.", image: "/images/service-heroes/20ft-shower-trailer-sink/01-960.webp", alt: "Actual shower stall inside a 20 ft temporary shower trailer", caption: "Approved 20 ft shower-trailer reference with commercial shower fixtures.", href: "/equipment-rental/shower-trailer/" },
  { eyebrow: "SHOWER CONTAINERS", title: "Containerized showers for extended projects.", text: "Plan private shower capacity for base camps, workforce sites and longer deployments.", image: "/media/equipment-drive/shower-containers/20ft-shower-container-5-stalls/mobile-shower-container-interior.png", alt: "Interior stalls in a 20 ft mobile shower container", caption: "Approved 20 ft shower-container reference; confirm stall count, utilities and access.", href: "/services/shower-containers/20ft-5-stall/" },
  { eyebrow: "COMBINATION UNITS", title: "Shower and restroom in one plan.", text: "Coordinate washing, restroom access, hot water, servicing and delivery around the actual site and occupancy.", image: "/images/service-heroes/13ft-shower-restroom-combination/01-960.webp", alt: "Interior of a 13 ft three-stall shower and restroom combination trailer", caption: "Approved 13 ft combination-trailer reference; confirm stall count and layout before booking.", href: "/services/shower-restroom-combination-trailers/" },
  { eyebrow: "WORKFORCE HOUSING", title: "Practical housing for working crews.", text: "Coordinate sleeper units and man-camp support around occupancy, shifts, utilities and project duration.", image: "/images/catalog/mobile-sleep-trailers-960.webp", alt: "Bunk beds inside a mobile workforce sleeper trailer", caption: "Approved sleeper-trailer reference; confirm occupancy, privacy and available unit.", href: "/man-camps-for-rent/" },
  { eyebrow: "MOBILE KITCHENS", title: "Commercial kitchens for active sites.", text: "Keep meal production moving through renovations, emergencies, events and remote projects.", image: "/images/service-heroes/24ft-mobile-kitchen/01-960.webp", alt: "Interior of a 24 ft mobile kitchen trailer", caption: "Approved 24 ft mobile-kitchen reference; confirm the equipment package and layout.", href: "/inventory/mobile-kitchen-models/" },
  { eyebrow: "REFRIGERATION TRAILERS", title: "Cold storage that keeps pace.", text: "Temperature-controlled space for ingredients, prepared food and critical supplies.", image: "/images/service-heroes/20ft-refrigerated-trailer/01-960.webp", alt: "Interior of a 20 ft refrigerated trailer", caption: "Approved refrigerated-trailer reference; confirm temperature range, power and access.", href: "/refrigeration/" },
  { eyebrow: "DISHWASHING TRAILERS", title: "High-volume warewashing support.", text: "Dedicated dishwashing capacity for food-service operations, events and emergency kitchens.", image: "/images/service-heroes/38ft-high-temp-dish/01-960.webp", alt: "Commercial dishwashing equipment inside a mobile dishwashing trailer", caption: "Approved commercial dishwashing-trailer reference; confirm wash capacity and utilities.", href: "/inventory/dishwashing-models/" },
  { eyebrow: "RESTROOM TRAILERS", title: "Comfortable restroom facilities.", text: "Dependable temporary restroom capacity for guests, staff and occupied facilities when permanent restrooms are unavailable.", image: "/images/catalog-supplied/restroom-trailers/01-960.webp", alt: "Toilet and wall-mounted sink inside a commercial mobile restroom trailer", caption: "Approved restroom-trailer interior reference; confirm the available unit and layout.", href: "/equipment-rental/restroom-trailers/" },
];
const industries = [
  ["CS", "Construction sites", "Keep crews clean and productive through multi-week and multi-month builds."],
  ["GM", "Government & military", "Support disaster response, public works, military and emergency-management operations."],
  ["EF", "Events & festivals", "Provide comfortable shower and restroom access for outdoor events, weddings and sporting programs."],
  ["HF", "Healthcare facilities", "Support staff hygiene during renovations, outages or emergency facility work."],
  ["EC", "Educational campuses", "Keep housing, athletics and campus operations moving during renovations or response work."],
  ["EI", "Energy & industrial", "Plan heavy-duty configurations, hot water and remote-site logistics for industrial operations."],
];
const faqs = [
  ["How much does a shower trailer rental cost?", "Pricing depends on the unit, occupancy, location, rental duration, site access, utilities and servicing plan. Share those details for a project-specific quote."],
  ["How quickly can a shower trailer be delivered?", "Delivery timing depends on availability, route, site readiness and the requested date. The rental team confirms the schedule before an agreement is finalized."],
  ["Are ADA-accessible shower trailers available?", "Accessible configurations may be available. Confirm the actual floor plan, access route, ramp and site requirements with the rental team."],
  ["Do you offer long-term shower trailer rentals?", "Yes. Discuss short-term or extended rental needs, servicing, delivery and removal timing with the project team."],
  ["Do you hold a GSA Schedule contract?", "Government buyers should confirm the current contract details and purchasing path with the rental specialist before relying on a procurement claim."],
];

export function Home() {
  return <div className="shower-home">
    <section className="shower-hero" aria-labelledby="shower-hero-title"><div className="shower-hero-panel"><span className="shower-kicker">TEMPORARY SHOWER RENTAL 123 · NATIONWIDE</span><h1 id="shower-hero-title">Temporary Shower Trailer Rentals Nationwide</h1><p>Rent mobile shower trailers, shower and restroom combination trailers, mobile kitchens, man camp and workforce housing units, refrigeration and freezer trailers, and temporary dishwashing facilities for planned projects and emergencies.</p><div className="shower-actions"><a className="button" href="/equipment-rental/">View Rental Equipment</a><a className="button secondary" href="/contact-us/">Request a Quote</a></div><div className="shower-hero-facts"><span><strong>24/7</strong> live agent support</span><span><strong>50</strong> states served</span><span><strong>Project</strong> delivery schedule confirmed</span></div></div><figure className="shower-hero-image"><img src="/images/service-heroes/20ft-shower-trailer-sink/01-960.webp" alt="Actual shower stall inside a temporary shower trailer" width="960" height="640" fetchPriority="high" /><figcaption>Actual shower stall with commercial fixtures inside a representative trailer.</figcaption></figure></section>
    <section className="shower-section shower-intro" aria-labelledby="solutions-title"><div><span className="shower-kicker">TEMPORARY FACILITY RENTALS</span><h2 id="solutions-title">Start with showers, then build the facility mix your site needs.</h2></div><p>Shower trailers and shower containers lead this rental portfolio. Supporting options include shower and restroom combinations, mobile kitchens, workforce housing, refrigeration and freezer trailers, temporary dishwashing facilities and restroom trailers. Confirm the available unit, utilities, access and delivery plan for your site.</p></section>
    <section className="shower-section shower-units" aria-labelledby="units-title"><div className="shower-section-heading"><div><span className="shower-kicker">EXPLORE THE FLEET</span><h2 id="units-title">Choose the facility mix your site needs.</h2></div><a className="text-link" href="/equipment-rental/">View all rental options ↗</a></div><div className="shower-unit-grid">{units.map((unit) => <article className="shower-unit-card" key={unit.href}><figure><img src={unit.image} alt={unit.alt} loading="lazy" width="960" height="640" /><figcaption>{unit.caption}</figcaption></figure><div><span className="shower-kicker">{unit.eyebrow}</span><h3>{unit.title}</h3><p>{unit.text}</p><a className="text-link" href={unit.href}>Explore this option ↗</a></div></article>)}</div></section>
    <section className="shower-facts" aria-label="Service facts"><div><strong>24/7</strong><span>Live agent support</span></div><div><strong>50</strong><span>States served</span></div><div><strong>Confirmed</strong><span>Project-specific delivery timing</span></div><div><strong>GSA</strong><span>Verify current contract details</span></div></section>
    <section className="shower-section" aria-labelledby="industries-title"><span className="shower-kicker">INDUSTRIES WE SERVE</span><h2 id="industries-title">Commercial shower trailers built around your operation.</h2><div className="shower-industry-grid">{industries.map(([code, title, text]) => <article key={title}><span className="shower-industry-code">{code}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section>
    <section className="shower-section shower-included" aria-labelledby="included-title"><div><span className="shower-kicker">WHAT'S INCLUDED</span><h2 id="included-title">Comfort, privacy and dependable site support.</h2></div><div className="shower-included-grid"><p><strong>Climate-controlled comfort</strong> Year-round heating and air conditioning for changing conditions.</p><p><strong>Continuous hot water</strong> Commercial-grade water heaters for every shift or guest.</p><p><strong>Private, secure stalls</strong> Individual lockable shower compartments for privacy.</p><p><strong>Accessible options</strong> Confirm the actual ADA layout and access requirements for the selected unit.</p><p><strong>Safety flooring</strong> Slip-resistant floors designed for clean, safe step-in showering.</p><p><strong>Self-contained supply</strong> Review onboard water, power, drainage and servicing for remote sites.</p></div></section>
    <section className="shower-section shower-faq" aria-labelledby="faq-title"><span className="shower-kicker">FREQUENTLY ASKED QUESTIONS</span><h2 id="faq-title">Clear answers before you schedule.</h2><div className="shower-faq-list">{faqs.map(([question, answer]) => <details key={question}><summary>{question}<span aria-hidden="true">+</span></summary><p>{answer}</p></details>)}</div></section>
    <section className="shower-cta" aria-labelledby="cta-title"><span className="shower-kicker">READY TO PLAN?</span><h2 id="cta-title">Need a temporary shower, restroom or bathroom trailer?</h2><p>Tell the logistics team about crew capacity, site footprint and scheduling.</p><div className="shower-actions"><a className="button" href={`tel:${site.phoneE164}`}>Call now: {site.phoneDisplay}</a><a className="button secondary" href="/contact-us/">Request a quote</a></div></section><p className="shower-disclaimer">Delivery timing, availability, pricing and contract terms require confirmation for the actual project.</p>
  </div>;
}
